env: standard
instance_class: F1
runtime: nodejs14
service: default
entrypoint: node --es-module-specifier-resolution=node ./build/index.js

handlers:
- url: /pckoubou/names

- url: /pckoubou/prices

- url: /pckoubou/id

  automatic_scaling:
  min_instances: 0
  max_instances: 0
