env: standard
instance_class: F1
runtime: nodejs14
service: default

handlers:
- url: /pckoubou/names
  script: auto

- url: /pckoubou/prices
  script: auto

- url: /pckoubou/id
  script: auto
